#!/bin/bash

git push origin :refs/tags/0,6
git push origin :refs/tags/0.1.1
git push origin :refs/tags/0.3
git push origin :refs/tags/0.4
git push origin :refs/tags/0.5
git push origin :refs/tags/0.6
git push origin :refs/tags/0.7
git push origin :refs/tags/1.1
git push origin :refs/tags/1.2
git push origin :refs/tags/1.2.2
git push origin :refs/tags/1.2.4
git push origin :refs/tags/1.3.5
git push origin :refs/tags/1.4.3
git push origin :refs/tags/1.4.6
git push origin :refs/tags/1.4.7
git push origin :refs/tags/1.4.8
git push origin :refs/tags/1.4.9
git push origin :refs/tags/1.5
git push origin :refs/tags/1.5.6
git push origin :refs/tags/1.6
git push origin :refs/tags/1.7.5
git push origin :refs/tags/1.8
git push origin :refs/tags/2.0
git push origin :refs/tags/2.1
git push origin :refs/tags/2.2
git push origin :refs/tags/2.3
git push origin :refs/tags/2.4
git push origin :refs/tags/5.1.3
git push origin :refs/tags/v.1.1.0
git push origin :refs/tags/v.5.0
git push origin :refs/tags/v.5.1
git push origin :refs/tags/v.5.1.10
git push origin :refs/tags/v.5.1.11
git push origin :refs/tags/v.5.1.12
git push origin :refs/tags/v.5.1.2
git push origin :refs/tags/v.5.1.4
git push origin :refs/tags/v.5.1.5
git push origin :refs/tags/v.5.1.6
git push origin :refs/tags/v.5.1.7
git push origin :refs/tags/v.5.1.8
git push origin :refs/tags/v.5.1.9
git push origin :refs/tags/v1.1.1
git push origin :refs/tags/v2.2
git push origin :refs/tags/v2.3
git push origin :refs/tags/v2.5
git push origin :refs/tags/v2.6
git push origin :refs/tags/v2.7
