steps:
  - name: antora/antora
    args:
      - '--fetch'
      - antora-playbook.yml
    id: antora-doc-creation
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y rsync git
        for version_dir in outputs/antora-db-doc/*; do
          if [ -d "$version_dir" ]; then
            echo "Processing version directory: $version_dir with tag"
            git clone --branch $(basename "$version_dir") https://github.com/azoom-taiga-sato/antora-db-doc.git temp_repo
            if [ $? -ne 0 ]; then
              echo "Failed to clone repository for tag"
              continue
            fi
            mkdir -p "$version_dir/schemaspy"
            rsync -av temp_repo/docs/schemaspy-raw/ "$version_dir/schemaspy/"
            if [ $? -ne 0 ]; then
              echo "Failed to copy files from schemaspy-raw for tag"
            else
              echo "Successfully copied files for tag"
            fi
            rm -rf temp_repo
          fi
        done
    id: create-schemaspy-index-file
    waitFor:
      - antora-doc-creation
    entrypoint: sh
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        echo "Contents of outputs directory:"
        find outputs -type d -print -o -type f -print
    id: echo-output-directory
    waitFor:
      - create-schemaspy-index-file
    entrypoint: sh
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--dockerfile=./cicd/dev/Dockerfile'
      - '--destination=gcr.io/${PROJECT_ID}/${_APP_NAME}:${_TAG_NAME}'
    id: build-app-image
    waitFor:
      - antora-doc-creation
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME}:${_TAG_NAME}
    id: deploy
    entrypoint: bash
timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _APP_DOCKER_FILE: cicd/dev/Dockerfile
  _TAG_NAME: latest
  _CLOUD_SQL_INSTANCES: 'azoom-taiga-satou:asia-northeast1:tbls-demo'
  _CLOUD_SQL_PROXY_IMAGE_NAME: 'gcr.io/cloudsql-docker/gce-proxy:1.35.4'
  _BASE_DIR: outputs/antora-db-doc
  _APP_NAME: antora-db-doc