steps:
  - id: prepare-socket-folder
    name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        mkdir /cloudsql || true
        chmod -R 777 /cloudsql
    entrypoint: bash
    volumes:
      - name: cloudsql
        path: /cloudsql
  - id: start-cloudsql-proxy
    name: '${_CLOUD_SQL_PROXY_IMAGE_NAME}'
    args:
      - /cloud_sql_proxy
      - '-dir=/cloudsql'
      - '-instances=${_CLOUD_SQL_INSTANCES}'
    waitFor:
      - prepare-socket-folder
    volumes:
      - name: cloudsql
        path: /cloudsql
  - id: migrate-database
    name: 'gcr.io/cloud-builders/yarn:node-20.11.0'
    env:
      - >-
        DATABASE_URL=mysql://taiga.satou:Z5DG81feVqN6@localhost/tbls_demo_box?socketPath=/cloudsql/$_CLOUD_SQL_INSTANCES
    args:
      - '-c'
      - >
        mv package.json package.json.bak && echo '{"dependencies":
        {"drizzle-orm": "0.31.2","drizzle-kit": "0.22.8","mysql2": "3.9.6"}}' >
        package.json && yarn && yarn drizzle-kit migrate
    waitFor:
      - prepare-socket-folder
    entrypoint: bash
    volumes:
      - name: cloudsql
        path: /cloudsql
  # - id: tbls-doc-creation
  #   name: 'ghcr.io/k1low/tbls'
  #   args:
  #       - '-c' 
  #       - | 
  #       tbls doc 'mysql://root:@localhost:3306/tbls_demo_box'

  - id: build-docker-image
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pandoc-converter', '-f', './cicd/dev/Dockerfile', '.']

  - id: convert-md-asciidoc
    name: 'gcr.io/$PROJECT_ID/pandoc-converter'
    entrypoint: 'bash'
    env: 
      - 'PANDOC_INPUT=docs'
      - 'PANDOC_OUTPUT=outputs'
    args:
      - '-c'
      - |
        chmod +x ./convert-tbls-doc.sh
        ./convert-tbls-doc.sh

# chmod +x convert_md_to_adoc.sh
# ./convert-tbls-doc.sh

  - id: antora-doc-creation
    name: 'antora/antora'
    args: 
      - --fetch
      - antora-playbook.yml
# docker run --rm --platform linux/amd64 -v $PWD:/work -w /work antora/antora antora --fetch antora-playbook.yml

  - id: build
    name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --dockerfile=./cicd/dev/Dockerfile
      - --destination=gcr.io/${PROJECT_ID}/${_APP_NAME}:${_TAG_NAME}

# docker build -t test -f ./cicd/dev/Dockerfile .
# docker run -p 3000:3000 test

  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME} \

substitutions:
  _APP_NAME: antora-db-doc
  _TAG_NAME: latest
timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY