steps:
  - id: init git for docs/antora-adoc
    name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      cd docs/antora-adoc
      if [ ! -d .git ]; then
        git init
      fi
      cd ../..
        
  # Fetch the Antora documentation
  - id: antora-doc-creation
    name: 'antora/antora'
    args: 
      - --fetch
      - antora-playbook.yml

  - id: create-schemaspy-index-file-each-branch
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Fetching all branches..."
        git fetch --all
        for branch in $(git branch -r | grep -v '\->'); do
          branch_name=$(echo $branch | sed 's/origin\///')
          echo "Checking out branch: $branch_name"
          git checkout $branch_name
          version=$(grep 'version:' docs/antora-adoc/antora.yml | sed 's/version: //')
          echo "Version in antora.yml is $version"
          if [ -z "$version" ]; then
            echo "Failed to retrieve version from antora.yml"
            exit 1
          fi
          version_dir="outputs/$version"
          if [ -d "$version_dir" ]; then
            echo "Creating schemaspy directory for version $version"
            mkdir -p "$version_dir/schemaspy"
            rsync -av docs/schemaspy-raw/ "$version_dir/schemaspy/"
          else
            echo "Version directory $version_dir does not exist."
          fi
        done
        
  # Build the app image via DockerFile (Container Registry is used)
  - id: build-app-image
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['antora-doc-creation']
    args:
      - --dockerfile=./cicd/dev/Dockerfile
      - --destination=gcr.io/${PROJECT_ID}/${_APP_NAME}:${_TAG_NAME}

  # Build the app image via DockerFile (Artifact Registry is used)
  # - id: build-app-image
  #   name: 'gcr.io/kaniko-project/executor:latest'
  #   waitFor: ['antora-doc-creation']
  #   args:
  #     - --dockerfile=${_APP_DOCKER_FILE}
  #     - --destination=asia-northeast1-docker.pkg.dev/azoom-taiga-satou/antora-demo:latest
  #     - --cache=true
      # Commands to run locally
        # docker build -t test -f ./cicd/dev/Dockerfile .
        # docker run -p 8080:8080 test

  # Deploy the app to Cloud Run
  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME}:${_TAG_NAME}

timeout: 900s
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _APP_NAME: antora-db-doc
  _APP_DOCKER_FILE: cicd/dev/Dockerfile
  _TAG_NAME: latest
  _CLOUD_SQL_INSTANCES: azoom-taiga-satou:asia-northeast1:tbls-demo
  _CLOUD_SQL_PROXY_IMAGE_NAME: 'gcr.io/cloudsql-docker/gce-proxy:1.35.4'
  _BASE_DIR: outputs/antora-db-doc