== user

=== Description

Users table

Table Definition

[source,sql]
----
CREATE TABLE `user` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `birthday` date NOT NULL,
  `plate_number` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attribute_id` bigint NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_email_unique` (`email`),
  KEY `user_attribute_id_attribute_id_fk` (`attribute_id`),
  KEY `name_idx` (`name`),
  CONSTRAINT `user_attribute_id_attribute_id_fk` FOREIGN KEY (`attribute_id`) REFERENCES `attribute` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
----

=== Labels

`+user+` `+privacy data+`

=== Columns

[width="100%",cols="9%,6%,11%,13%,26%,13%,11%,11%",options="header",]
|===
|Name |Type |Default |Nullable |Extra Definition |Children |Parents
|Comment
|id |bigint | |false |auto_increment | | |

|name |varchar(50) | |false | | | |

|email |varchar(50) | |false | | | |Email address as login id. ex.
user@example.com

|email_verified |varchar(50) | |true | | | |

|password |varchar(255) | |false | | | |

|birthday |date | |false | | | |

|plate_number |varchar(50) | |false | | | |

|attribute_id |bigint | |false | | |link:attribute.md[attribute] |

|created_at |timestamp | |true | | | |

|updated_at |timestamp | |true | | | |

|deleted_at |timestamp | |true | | | |
|===

=== Viewpoints

[cols=",",options="header",]
|===
|Name |Definition
|link:viewpoint-0.md[User情報] |User情報に関するドキュメント
|===

=== Constraints

[width="100%",cols="23%,22%,55%",options="header",]
|===
|Name |Type |Definition
|PRIMARY |PRIMARY KEY |PRIMARY KEY (id)

|user_attribute_id_attribute_id_fk |FOREIGN KEY |FOREIGN KEY
(attribute_id) REFERENCES attribute (id)

|user_email_unique |UNIQUE |UNIQUE KEY user_email_unique (email)
|===

=== Indexes

[width="100%",cols="29%,71%",options="header",]
|===
|Name |Definition
|name_idx |KEY name_idx (name) USING BTREE

|user_attribute_id_attribute_id_fk |KEY
user_attribute_id_attribute_id_fk (attribute_id) USING BTREE

|PRIMARY |PRIMARY KEY (id) USING BTREE

|user_email_unique |UNIQUE KEY user_email_unique (email) USING BTREE
|===

=== Relations

.er
image::user.svg[]

'''''

____
Generated by https://github.com/k1LoW/tbls[tbls]
____
