name: Update version and tag
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "::set-output name=version::$VERSION"

      - name: Update antora.yml version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i "s/^version: .*/version: ${VERSION}/" docs/antora.yml

      - name: Commit changes
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/antora.yml
          git commit -m "Update version to ${VERSION}"

      - name: Push changes
        run: |
          git push origin HEAD:refs/heads/main

      - name: Create and push tag
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          git tag v$VERSION
          git push origin v$VERSION