name: Generate Antora Docs & Update Version

on:
  push:
    branches-ignore:
      - main
env:
  DB_NAME: parking

jobs:
  doc-creation:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      # Database migration (remove "--> statement-breakpoint" if it is included in the migration file)
      - name: Apply Migrations
        run: |
          for file in drizzle/migrations/*.sql; do
            if grep -q 'statement-breakpoint' "$file"; then
              tmp_file=$(mktemp)
              sed 's/--> statement-breakpoint//g' "$file" > "$tmp_file"
              mysql -h 127.0.0.1 -u root ${{ env.DB_NAME }} < "$tmp_file" && echo "Applied $file" || exit 1
              rm "$tmp_file"
            else
              mysql -h 127.0.0.1 -u root ${{ env.DB_NAME }} < "$file" && echo "Applied $file" || exit 1
            fi
          done

      # Setup tbls
      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      # Run tbls doc
      - name: Run tbls doc
        env:
          DSN: 'mysql://root@localhost:3306/${{ env.DB_NAME }}'
        run: tbls doc --force

      - name: Pull pandoc/core Docker image
        run: docker pull pandoc/core
  
      - name: Set execute permission for the script
        run: chmod +x convert-tbls-doc.sh
  
      - name: Run the script to convert the tbls documentation
        run: ./convert-tbls-doc.sh

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Set tag name
        id: set_tag_name
        run: echo "TAG_NAME=docv-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Set execute permission for the script
        run: chmod +x exec-schemaspy.sh
      
      - name: Run the script to generate SchemaSpy documentation
        run: ./exec-schemaspy.sh ${{ env.VERSION }}
        env:
          DB_NAME: ${{ env.DB_NAME }}
          TAG_NAME: ${{ env.TAG_NAME }}

      - name: Update version in antora.yml
        run: |
          sed -i 's/version: .*/version: '"${{ env.TAG_NAME }}"'/' docs/antora-adoc/antora.yml
        
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update doc version to ${{ env.TAG_NAME }}"
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ github.ref_name }} ${{ env.TAG_NAME }}
          git push origin HEAD:${{ github.ref_name }}