name: ci
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update antora.yml version
        run: |
          TAG=$(git describe --tags)
          sed -i "s/^version: .*/version: ${TAG}/" docs/antora.yml

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docs/antora.yml
          git commit -m "Update version to ${TAG}"

      - name: Push changes
        run: |
          git push origin HEAD